backend:
  name: github
  repo: rapidfawn2489/voltnetworks-addons
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "store"
    label: "VoltNetworks Store"
    files:
      - name: "addons"
        label: "Add-ons"
        file: "addons.json"
        format: "json"
        fields:
          - label: "Add-ons"
            name: ""
            widget: "list"
            summary: "{{fields.name}} - £{{fields.price}}"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Tag", name: "tag", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Features"
                name: "features"
                widget: "list"
                field: { label: "Feature", name: "feature", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Currency", name: "currency", widget: "string", default: "GBP" }
              - { label: "Image", name: "image", widget: "image", required: false }
